### ISSUE TITLE
Build failure, July 5

### ISSUE THREAD

**Issue by maqifrnswa** [LibreCAD/LibreCAD#91]
Caused by commit fc5da547839bd5d0ccbf

full text:
https://code.launchpad.net/~librecad-dev/+archive/librecad-daily/+build/2610602

g++ -c -pipe -g -O2 -Wall -W -D_REENTRANT -DQC_APPKEY="/LibreCAD" -DQC_APPNAME="LibreCAD" -DQC_COMPANYNAME="LibreCAD" -DQC_COMPANYKEY="LibreCAD" -DQC_VERSION="1.0.0rc1" -DQC_DELAYED_SPLASH_SCREEN=1 -DQC_SCMREVISION="" -DQC_APPDIR="librecad" -DQINITIMAGES_LIBRECAD=qInitImages_librecad -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtHelp -Idxflib/src -Ifparser -Isrc/cmd -Isrc/lib/actions -Isrc/lib/creation -Isrc/lib/debug -Isrc/lib/engine -Isrc/lib/fileio -Isrc/lib/filters -Isrc/lib/gui -Isrc/lib/information -Isrc/lib/math -Isrc/lib/modification -Isrc/lib/scripting -Isrc/actions -Isrc/main -Isrc/plugins -Isrc/ui -Isrc/ui/forms -Ires -Iintermediate/moc -Iintermediate/ui -o intermediate/obj/rs_constructionline.o src/lib/engine/rs_constructionline.cpp
src/lib/engine/rs_circle.cpp: In member function 'virtual void RS_Circle::draw(RS_Painter_, RS_GraphicView_, double)':
src/lib/engine/rs_circle.cpp:328:20: error: 'patternSelected' was not declared in this scope
src/lib/engine/rs_circle.cpp:352:28: error: invalid use of incomplete type 'struct RS_LineTypePattern'
src/lib/gui/rs_graphicview.h:41:7: error: forward declaration of 'struct RS_LineTypePattern'
src/lib/engine/rs_circle.cpp:354:24: error: invalid use of incomplete type 'struct RS_LineTypePattern'
src/lib/gui/rs_graphicview.h:41:7: error: forward declaration of 'struct RS_LineTypePattern'
src/lib/engine/rs_circle.cpp:355:29: error: invalid use of incomplete type 'struct RS_LineTypePattern'
src/lib/gui/rs_graphicview.h:41:7: error: forward declaration of 'struct RS_LineTypePattern'
src/lib/engine/rs_circle.cpp:368:20: error: invalid use of incomplete type 'struct RS_LineTypePattern'
src/lib/gui/rs_graphicview.h:41:7: error: forward declaration of 'struct RS_LineTypePattern'
src/lib/engine/rs_circle.cpp:386:23: error: invalid use of incomplete type 'struct RS_LineTypePattern'
src/lib/gui/rs_graphicview.h:41:7: error: forward declaration of 'struct RS_LineTypePattern'
