### PR TITLE
Fix compile with gcc 5.4

### PR DESCRIPTION
**Pull request by rezso**
lib/engine/rs_spline.cpp:592:2: error: 'iota' is not a member of 'std'
include numeric c++ header solves this.

### CODE REVIEW

**Comment by lordofbikes** [comment]
Thanks for fixing this.
