### ISSUE TITLE
not able to compile with qt5.6 with vsc2015 on windows 

### ISSUE THREAD

**Issue by gth802m** [LibreCAD/LibreCAD#703]
..LibreCAD\libraries\jwwlib\src\jwwdoc.cpp:7: error: C2511: 'void CDataSen::Serialize(std::ofstream &)': overloaded member function not found in 'CDataSen'.

**Comment by r-a-v-a-s** [comment]
https://github.com/LibreCAD/LibreCAD/issues/696

**Comment by gth802m** [comment]
thanks

**Comment by lordofbikes** [comment]
Closing this, with follow up to issue #914, MSVC is still not supported
